image: registry.gitlab.com/panw-gse/as/panos_skillet_tools:latest

before_script:
  - python -V  # Print out python version for debugging

test:
  script:
    - ansible-playbook -i inventory.sample license-airgap-firewall.yml --syntax-check
    - ansible-lint license-airgap-firewall.yml -v
