name: panos_license_airgapped_firewall
label: License a Airgapped NGFW
description: |
  Workflow that registers a VM with the Licensing API and pushes
  the license keys to the VM.
type: docker

labels:
  collection: Deploy Tools

variables:
  - name: ip_address
    description: Host IP Address
    default: 10.10.10.10
    type_hint: ip_address

  - name: username
    description: Host Username
    default: admin
    type_hint: text

  - name: password
    description: Host Password
    default: admin
    type_hint: password

  - name: api_key
    description: Support Portal Licensing API Key
    default: SOMECODEHERE
    type_hint: text

  - name: first_time_registration
    description: Is this the first time or initial license activation?
    default: 'Yes'
    type_hint: dropdown
    help_text: |
      If you did not save the license keys or had a network connection trouble
      during initial license activation, to retrieve the license(s) again for a
      firewall that you have previously activated, choose no.
    dd_list:
      - key: 'Yes'
        value: 'Yes'
      - key: 'No'
        value: 'No'

  - name: auth_code
    description: Auth Code
    default: SOMECODEHERE
    type_hint: text
    toggle_hint:
      source: first_time_registration
      value: 'Yes'

  - name: serial_num
    description: FW Serial Number
    default: unknown
    type_hint: text
    toggle_hint:
      source: first_time_registration
      value: 'No'


snippets:
  - name: ansible_test
    image: registry.gitlab.com/panw-gse/as/panos_skillet_tools:dev
    async: True
    cmd: |
      ansible-playbook -i 'panos,' license-airgap-firewall.yml
      -e 'auth_code="{{ auth_code }}"'
      -e 'api_key="{{ api_key }}"'
      -e 'serial_num="{{ serial_num }}"'