---
- hosts: fw
  connection: local

  vars:
    auth_code: '{{ auth_code }}'
    api_key: '{{ api_key }}'
    first_time: '{{ first_time }}'


  collections:
    - mrichardson03.panos


  tasks:
    - name: Include User Variables
      include_vars: vars/main.yml

    - name: Check if device is ready
      panos_check:

    - name: View System Info
      panos_op:
        cmd: 'show system info'
      register: system_info_response

    - name: Set JSON System Info
      set_fact:
        system_info: "{{ system_info_response.stdout | from_json  }}"

    - name: Grab System Info
      set_fact:
        vm_uuid:  "{{ system_info.response.result.system['vm-uuid'] }}"
        vm_cpuid:  "{{  system_info.response.result.system['vm-cpuid'] }}"
        vm_serial: "{{ system_info.response.result.system['serial'] }}"

    - name: Activate VM Licenses with API
      uri:
        url: https://api.paloaltonetworks.com/api/license/activate
        method: POST
        headers:
          apiKey: '{{ api_key }}'
        body_format: form-urlencoded
        body:
          cpuid: '{{ vm_cpuid }}'
          uuid: '{{ vm_uuid }}'
          authCode: '{{ auth_code }}'
      register: reg
      when: first_time == "yes"

    - name: Retrieve Previously Activated Licenses with API
      uri:
        url: https://api.paloaltonetworks.com/api/license/activate
        method: POST
        headers:
          apiKey: '{{ api_key }}'
        body_format: form-urlencoded
        body:
          cpuid: '{{ vm_cpuid }}'
          uuid: '{{ vm_uuid }}'
      register: rereg
      when: first_time == "no"

    - name: Save API Response
      set_fact:
        key_list: "{% if first_time=='yes' %}{{ reg.json }}{% else %}{{ rereg.json }}{% endif %}"

    - name:
      block:
        - name: Push license keys to Firewall
          panos_op:
            cmd: '<request><license><install>{{ item.keyField }}</install></license></request>'
            cmd_is_xml: true
          loop: '{{ key_list }}'
          loop_control:
            pause: 1
      rescue:
        - name: Pause for reboot check
          pause:
            seconds: 30

        - name: Check if device is up and ready
          panos_check: