name: license_airgapped_fw
label: License Air-Gapped Workflow
description: |
  This workflow steps through the elements to license a FW
  that is not connected to the Internet.

type: workflow

labels:
    collection:
      - Deploy Tools

variables:
  - name: TARGET_IP
    description: NGFW IP or Hostname
    default: 192.168.55.10
    type_hint: fqdn_or_ip
  - name: TARGET_USERNAME
    description: NGFW Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: NGFW Password
    default: admin
    type_hint: password
  - name: auth_code
    description: Auth Code
    default: SOMECODEHERE
    type_hint: text


snippets:
  # get existing device values for licensing
  - name: gather_vm_info

  # reach out to license API to gather license files
  #- name: fetch_license_from_api

  # push the license files to the NGFW for licensing
  #- name: push_license_files_to_fw
