name: gather_vm_info
label: Gather VM Info
description: |
    Queries firewall for CPUID, UUID, Hostname

type: panos

labels:
    collection: lib

variables:
  - name: TARGET_IP
    description: NGFW IP or Hostname
    default: 192.168.55.10
    type_hint: hidden
  - name: TARGET_USERNAME
    description: NGFW Username
    default: admin
    type_hint: hidden
  - name: TARGET_PASSWORD
    description: NGFW Password
    default: admin
    type_hint: hidden

snippets:
  - name: get_system_info
    cmd: cli
    cmd_str: show system info
    output_type: xml
    outputs:
      - name: uuid
        capture_value: /system/vm-uuid/text()
      - name: cpuid
        capture_value: /system/vm-cpuid/text()
      - name: hostname
        capture_value: /system/hostname/text()
      - name: serial_number
        capture_value: /system/serial/text()