name: push_license_files_to_fw
label: Push License Key to FW
description: |
    Push license keys to NGFW

type: panos

labels:
  collection: lib

variables:
  - name: TARGET_IP
    description: NGFW IP or Hostname
    default: 192.168.55.10
    type_hint: hidden
  - name: TARGET_USERNAME
    description: NGFW Username
    default: admin
    type_hint: hidden
  - name: TARGET_PASSWORD
    description: NGFW Password
    default: admin
    type_hint: hidden
  - name: key_list
    description: key_list
    type_hint: hidden
  - name: key
    description: key
    type_hint: text
    default: KqyuRUB+fgBj8liR1Stp969wzwMTx47Q7matc/DNjo3GbBYegm/3O47vtuxkO3qB\nUs3p9u9oI3CccFPS4sd3+65END9amjXB6aBD/2J92cC5A+xmM+qenPGHYSIowo/V\nyWfgfzWDVioMaJoPnDRpBkl2Ze2/YEjLw4PKuLkG9tvsBRFRRVq2HPpQ5rDuyGez\nhhyPdxOUuTwrRcwbad4GOgpSQdwVrc8XDeYoAzXhXIs/FZzauwZ6KSt4FqQJ5nq6\n5EdPo5u74IVRsoNoq/B3Ar8jskiu9Uu0rMy7rTKBggDW/eCau7cvKQ9jL0zhkz37\nwhTPXIJiEzkPO9tRuF9vPw==\n
    help_text: ''

snippets:
  - name: format_key
    cmd: parse
    variable: key
    outputs:
      - name: formatted_key
        capture_variable: |-
          {{ key | replace('\\n', '\n') }}
      - name: formatted_key_list
        capture_variable: |-
          {%- for line in key.split('\\n') %}
          {{ line }}
          {%- endfor -%}

  - name: push_to_fw
    cmd: op
    cmd_str: <request><license><install>{{ key | replace("\\n", "\n") }}</install></license></request>
