name: push_license_key
label: Push License Key to FW
description: |
    Push license keys to NGFW

type: panos

labels:
    collection: lib

variables:
  - name: TARGET_IP
    description: NGFW IP or Hostname
    default: 192.168.55.10
    type_hint: hidden
  - name: TARGET_USERNAME
    description: NGFW Username
    default: admin
    type_hint: hidden
  - name: TARGET_PASSWORD
    description: NGFW Password
    default: admin
    type_hint: hidden
  - name: key_list
    type_hint: hidden

snippets:
  - name: format_cli_command
    cmd: parse
    variable: key_list
    output_type: text
    outputs:
      - name: push_command
        capture_variable: |-
          {%- set command = 'request license install' %}
          {%- for key in key_list %}
            {%- command = command ~ key ~ %}
          {%- endfor %}
          {{ command }}

  - name: push_command_to_fw
    cmd: cli
    cmd_str: {{ push_command }}