name: push_license_files_to_fw
label: Push License Key to FW
description: |
    Push license keys to NGFW

type: panos

labels:
  collection: lib

variables:
  - name: TARGET_IP
    description: NGFW IP or Hostname
    default: 192.168.55.10
    type_hint: hidden
  - name: TARGET_USERNAME
    description: NGFW Username
    default: admin
    type_hint: hidden
  - name: TARGET_PASSWORD
    description: NGFW Password
    default: admin
    type_hint: hidden
  - name: key_list
    default: bWIrUcaKO2uJ9gJBizHcUWfvZRVgcPYtIuzD8ihcwAS0e84hYd8Z0Jn9YbLoCam2\n3OHGR6rKLZQag81pRKNbASLKc0RrNDwSkwwYOijaZtMyrIvRuLJJpLDBtDzCDtxI\n4e4qqQ5Uz9e+U/z/e7eAiPjALvOAvgZBw11WS1PrHw3KeQ1NxVZrXAeFH3EXiAMP\noPoLEowOrYNE+9+/uV1bi/Kpb8XJ/Iifvi7Xn0KKxDv0d+EGprB6RYYx5xxSVbud\nS2KKT19w+L2O7FumKJULy++fFRVSMrDX3opVS5oXB6vx2jDVcvbx62QuUO553maS\nxNIU1dN8KriXAD10zyaJvA==\n
    type_hint: text

snippets:
#  - name: save_one_key
#    cmd: parse
#    variable: key_list
#    outputs:
#      - name: key_command
#        capture_variable: {% autoescape false %}{{ key_list|replace('\n', '\r\n') }}{% endautoescape %}

  - name: push_command_to_fw
    cmd: op
    cmd_str: <request><license><install>{% autoescape false %}{{ key_list|replace('\n', '\r\n') }}{% endautoescape %}</install></license></request>
