name: register_vm_support_api

label: Register VM to support portal API

description: |
  Registers a VM to the support portal

type: rest

labels:
  collection: lib

variables:
  - name: auth_code
    type_hint: hidden
  - name: support_api_key
    type_hint: hidden
  - name: uuid
    type_hint: hidden
  - name: cpuid
    type_hint: hidden

snippets:
  - name: register_vm
    path: https://api.paloaltonetworks.com/api/license/activate
    operation: post
    payload: project_payload.j2
    headers:
      apiKey: '{{ support_api_key }}'
      Content-Type: application/x-www-form-urlencoded
    output_type: json
    outputs:
      - name: full_output_as_json
        capture_object: .
      - name: key_pattern
        capture_pattern: $..keyField
      - name: key_object
        capture_object: $..keyField